name: Bug Report/Feature Request Form
description: Provide feedback to report bugs or request features
labels: [Bug/Issue, Feature Request]
title: Bug Report/Feature Request Form
assignees:
  - nguyen-anthony
body:
  - type: markdown
    attributes:
      value:
        Please provide as much detail as possible regarding your issue or feature request
  - type: textarea
    id: description
    attributes:
      label: Details/Description of Bug/Issue or Feature Request
      render: shell
    validations:
      required: true
  - type: dropdown
    id: reportType
    attributes:
      label: What kind of report is this?
      options:
        - Bug/Issue
        - Feature Request
    validations:
      required: true
